const constants = {
    API_Error : "There must be some issue. Data didn't retrieve.",
    username_already_exists : 'Username Already Exists',
    user_added: 'User Added Successfully',
    username_password_error: 'Wrong Username or Password',
    go_back: "Go Back",
    logout: "Logout",
    create_new_post: "Create New Post",
    close_the_dialog: "Close The Dialog",
    publish_the_post: "Publish The Post",
    new_post: "New Post",
    loading: "Loading ...",
    comments: "Comments",
    publish_the_comment: "Publish The Comment",
    login: "Login",
    edit_done: "Edit Done",
    edit_post: "Edit Post",
    data_loading_failed: "Data Loading Failed",
    username: "Username",
    full_name: "Full Name",
    password: "Password",
    enter_full_name: "Enter Full Name",
    enter_username: "Enter Username",
    enter_password: "Enter Password",
    not_logged_in: "You are not logged In",
    edit: "Edit",
    delete: "Delete",
    post: "Post",
    title: "Title",
    body: "Body",
    sign_up: "Sign Up",
    login_to_your_account: "Login To Your Account",
    join_us: "Are you new? Join us today.",
    blog_app: "BLOG APP",
    add_new_comment: "Add new comment"
}

export default constants